import P1 from "../assets/P1.jpg"
import P2 from "../assets/P2.jpg"
import P3 from "../assets/P3.png"
import P4 from "../assets/P4.png"

import P41 from "../assets/P41.png"
import P42 from "../assets/P42.png"
import P43 from "../assets/P43.png"
import P44 from "../assets/P44.png"
import P45 from "../assets/P45.png"
import P46 from "../assets/P46.png"
import P47 from "../assets/P47.png"
import P48 from "../assets/P48.png"

import P51 from "../assets/P51.png"
import P52 from "../assets/P52.png"
import P53 from "../assets/P53.png"
import P54 from "../assets/P54.png"
import P55 from "../assets/P55.png"
import P56 from "../assets/P56.png"
import P57 from "../assets/P57.png"
import P58 from "../assets/P58.png"

import P61 from "../assets/P61.png"
import P62 from "../assets/P62.png"
import P63 from "../assets/P63.png"
import P64 from "../assets/P64.png"
import P65 from "../assets/P65.png"
import P66 from "../assets/P66.png"
import P67 from "../assets/P67.png"
import P68 from "../assets/P68.png"




const Products = [
    {
        id: 1,
        product_name: "Built-in Ceramic Hot Plate",
        image: P1,
        description:
            "A flush mount ceramic glass hot plate designed for buffet setups, offering flame-free warming with robust build quality and efficient heat transfer.",
        features: [
            "Flush mount ceramic glass to help hide installations",
            "Ceramic glass surface for easy cleaning",
            "Moderate heat transfer to induction range for optimum serving",
            "Dual ceramic surface for holding and serving areas",
            "Manually adjustable holding surface via digital thermostat controller (optional)",
            "Optional white frame for aesthetic versatility",
            "Advanced control box with ON/OFF rocker switch and mounting brackets",
            "Available in black or white ceramic glass",
            "User friendly interface with digital controller",
        ],
        models: [
            {
                model: "CBS3838",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 380, W: 380, H: 90 },
                voltage: "230V",
                power: "450W",
                cut_out_size_AXB: "388x388",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS4040",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 400, W: 400, H: 90 },
                voltage: "230V",
                power: "500W",
                cut_out_size_AXB: "408x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS6040",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 600, W: 400, H: 90 },
                voltage: "230V",
                power: "750W",
                cut_out_size_AXB: "608x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS6050",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 600, W: 500, H: 90 },
                voltage: "230V",
                power: "1000W",
                cut_out_size_AXB: "608x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS8040",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 800, W: 400, H: 90 },
                voltage: "230V",
                power: "1050W",
                cut_out_size_AXB: "808x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS8050",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 800, W: 500, H: 90 },
                voltage: "230V",
                power: "1350W",
                cut_out_size_AXB: "808x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS9040",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 920, W: 400, H: 90 },
                voltage: "230V",
                power: "1200W",
                cut_out_size_AXB: "928x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS9050",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 920, W: 500, H: 90 },
                voltage: "230V",
                power: "1550W",
                cut_out_size_AXB: "928x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS12040",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 1200, W: 400, H: 90 },
                voltage: "230V",
                power: "1600W",
                cut_out_size_AXB: "1208x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS12050",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 1200, W: 500, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1208x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS15040",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 1500, W: 400, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1508x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS15050",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 1500, W: 500, H: 90 },
                voltage: "230V",
                power: "2600W",
                cut_out_size_AXB: "1508x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS18040",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 1843, W: 400, H: 90 },
                voltage: "230V",
                power: "2500W",
                cut_out_size_AXB: "1851x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS18050",
                image: P1,
                description: "Ceramic + Hotplate",
                dimensions: { L: 1843, W: 500, H: 90 },
                voltage: "230V",
                power: "3200W",
                cut_out_size_AXB: "1851x580",
                controller_size_AXBxC: "160x90x80",
            }
        ],
    },

    {
        id: 2,
        product_name: "Drop-in Ceramic Hot Plate",
        image: P2,
        description:
            "Efficient ceramic hot plate for buffet counters with adjustable thermostat and easy installation.",
        features: [
            "Safe and efficient infrared heating",
            "Digital temperature control option",
            "Reduces mess by replacing open flame",
            "Durable ceramic glass surface",
            "Can be installed by drop-in method",
            "Ceramic inlay available in black or white",
            "Standard size compatible mounting brackets",
        ],
        models: [
            {
                model: "CDS6040",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 646, W: 446, H: 90 },
                voltage: "230V",
                power: "750W",
                cut_out_size_AXB: "610x410",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS6050",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 646, W: 546, H: 90 },
                voltage: "230V",
                power: "1000W",
                cut_out_size_AXB: "610x510",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS8040",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 846, W: 446, H: 90 },
                voltage: "230V",
                power: "1050W",
                cut_out_size_AXB: "810x410",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS8050",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 846, W: 546, H: 90 },
                voltage: "230V",
                power: "1350W",
                cut_out_size_AXB: "810x510",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS9040",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 966, W: 446, H: 90 },
                voltage: "230V",
                power: "1200W",
                cut_out_size_AXB: "930x410",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS9050",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 966, W: 546, H: 90 },
                voltage: "230V",
                power: "1550W",
                cut_out_size_AXB: "930x510",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS12040",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1246, W: 446, H: 90 },
                voltage: "230V",
                power: "1600W",
                cut_out_size_AXB: "1210x410",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS12050",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1246, W: 546, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1210x510",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS15040",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1546, W: 446, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1510x410",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS15050",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1546, W: 546, H: 90 },
                voltage: "230V",
                power: "2600W",
                cut_out_size_AXB: "1510x510",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS18040",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1889, W: 446, H: 90 },
                voltage: "230V",
                power: "2500W",
                cut_out_size_AXB: "1853x410",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS18050",
                image: P2,
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1889, W: 546, H: 90 },
                voltage: "230V",
                power: "3200W",
                cut_out_size_AXB: "1853x510",
                controller_size_AXBxC: "160x90x80",
            }
        ],
    },
    {
        id: 3,
        product_name: "Ceramic Hot Plates with Thermal Bridge",
        image: P3,
        description:
            "Ceramic hot plate with additional thermal bridge heating for enhanced holding and staged warming.",
        features: [
            "Built in high performance quartz lamps for pre-heating",
            "Ceramic glass surface for high storage and hygiene",
            "Temperature output from hot plate and bridge area",
            "Digital/manual temperature control options",
            "Optimal energy saving",
            "Mountable on adjustable stands",
        ],
        models: [
            {
                model: "CTB06040",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 686, W: 486, H: "90+450" },
                voltage: "230V",
                power: "750W",
                cut_out_size_AXB: "606x406",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB6050",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 686, W: 586, H: "90+450" },
                voltage: "230V",
                power: "1000W",
                cut_out_size_AXB: "606x506",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB8040",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 886, W: 486, H: "90+450" },
                voltage: "230V",
                power: "1050W",
                cut_out_size_AXB: "806x406",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB8050",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 886, W: 586, H: "90+450" },
                voltage: "230V",
                power: "1350W",
                cut_out_size_AXB: "806x506",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB9040",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1006, W: 486, H: "90+450" },
                voltage: "230V",
                power: "1200W",
                cut_out_size_AXB: "926x406",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB9050",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1006, W: 586, H: "90+450" },
                voltage: "230V",
                power: "1550W",
                cut_out_size_AXB: "926x506",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB12040",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1289, W: 486, H: "90+450" },
                voltage: "230V",
                power: "1600W",
                cut_out_size_AXB: "1209x406",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB12050",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1289, W: 586, H: "90+450" },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1209x506",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB15040",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1589, W: 486, H: "90+450" },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1509x406",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB15050",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1589, W: 586, H: "90+450" },
                voltage: "230V",
                power: "2600W",
                cut_out_size_AXB: "1509x506",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB18040",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1889, W: 486, H: "90+450" },
                voltage: "230V",
                power: "2500W",
                cut_out_size_AXB: "1809x406",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB18050",
                image: P3,
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1889, W: 586, H: "90+450" },
                voltage: "230V",
                power: "3200W",
                cut_out_size_AXB: "1809x506",
                controller_size_AXBxC: "160x90x80",
            }
        ],
    },

    {
        id: 4,
        product_name: "Heated Decorative Lamps",
        image: P41,
        description: "Decorative lamps that provide uniform heating while enhancing food display aesthetics.",
        features: [
            "Integrates decoration, lighting, and warming functions for enhanced visual appeal.",
            "Allows flexible matching with different styles and colors.",
            "Available in a wide range of shades, gloss finishes, and plated options to match décor.",
            "Features heat dissipation holes to protect the main structure and extend service life.",
            "Provides even heating and effectively inhibits bacterial growth.",
            "Suitable for hotels, restaurants, institutional food courts, staff cafeterias, and similar environments.",
            "Standard height ranges from 320mm to 3245mm with customizable options.",
            "Complies with safety, health, environmental, and hygiene standards."
        ],
        models: [
            {
                model: "SKS-400-TL",
                diameter_mm: 180,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P41,
            },
            {
                model: "SKS-500-TL",
                diameter_mm: 165,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P42,
            },
            {
                model: "SKS-600-TL",
                diameter_mm: 175,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P43,
            },
            {
                model: "SKS-700-TL",
                diameter_mm: 175,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P44,
            },
            {
                model: "SKS-725-TL",
                diameter_mm: 240,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P45,
            },
            {
                model: "SKS-750-TL",
                diameter_mm: 285,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P46,
            },
            {
                model: "SKS-775-TL",
                diameter_mm: 265,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P47,
            },
            {
                model: "SKS-800-TL",
                diameter_mm: 285,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P48,
            },
        ],
    },
    {
        id: 5,
        product_name: "Heated Decorative Lamps",
        image: P51,
        description: "Decorative lamps that provide uniform heating while enhancing food display aesthetics.",
        features: [
            "Integrates decoration, lighting, and warming functions for enhanced visual appeal.",
            "Allows flexible matching with different styles and colors.",
            "Available in a wide range of shades, gloss finishes, and plated options to match décor.",
            "Features heat dissipation holes to protect the main structure and extend service life.",
            "Provides even heating and effectively inhibits bacterial growth.",
            "Suitable for hotels, restaurants, institutional food courts, staff cafeterias, and similar environments.",
            "Standard height ranges from 320mm to 3245mm with customizable options.",
            "Complies with safety, health, environmental, and hygiene standards."
        ],
        models: [
            {
                model: "SKS-400-ML",
                diameter_mm: 180,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P51,
            },
            {
                model: "SKS-500-ML",
                diameter_mm: 165,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P52,
            },
            {
                model: "SKS-600-ML",
                diameter_mm: 175,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P53,
            },
            {
                model: "SKS-700-ML",
                diameter_mm: 175,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P54,
            },
            {
                model: "SKS-725-ML",
                diameter_mm: 240,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P55,
            },
            {
                model: "SKS-750-ML",
                diameter_mm: 285,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P56,
            },
            {
                model: "SKS-775-ML",
                diameter_mm: 265,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P57,
            },
            {
                model: "SKS-800-ML",
                diameter_mm: 285,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P58,
            },
        ],
    },

    {
        id: 6,
        product_name: "Heated Decorative Lamps",
        image: P61,
        description: "Decorative lamps that provide uniform heating while enhancing food display aesthetics.",
        features: [
            "Integrates decoration, lighting, and warming functions for enhanced visual appeal.",
            "Allows flexible matching with different styles and colors.",
            "Available in a wide range of shades, gloss finishes, and plated options to match décor.",
            "Features heat dissipation holes to protect the main structure and extend service life.",
            "Provides even heating and effectively inhibits bacterial growth.",
            "Suitable for hotels, restaurants, institutional food courts, staff cafeterias, and similar environments.",
            "Standard height ranges from 320mm to 3245mm with customizable options.",
            "Complies with safety, health, environmental, and hygiene standards."
        ],
        models: [
            {
                model: "SKS-400-ST",
                diameter_mm: 180,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P61,
            },
            {
                model: "SKS-500-ST",
                diameter_mm: 165,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P62,
            },
            {
                model: "SKS-600-ST",
                diameter_mm: 175,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P63,
            },
            {
                model: "SKS-700-ST",
                diameter_mm: 175,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P64,
            },
            {
                model: "SKS-725-ST",
                diameter_mm: 240,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P65,
            },
            {
                model: "SKS-750-ST",
                diameter_mm: 285,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P66,
            },
            {
                model: "SKS-775-ST",
                diameter_mm: 265,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P67,
            },
            {
                model: "SKS-800-ST",
                diameter_mm: 285,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
                image: P68,
            },
        ],
    },
];

export default Products;