const Products = [
    {
        product_name: "Built-in Ceramic Hot Plate",
        description:
            "A flush mount ceramic glass hot plate designed for buffet setups, offering flame-free warming with robust build quality and efficient heat transfer.",
        features: [
            "Flush mount ceramic glass to help hide installations",
            "Ceramic glass surface for easy cleaning",
            "Moderate heat transfer to induction range for optimum serving",
            "Dual ceramic surface for holding and serving areas",
            "Manually adjustable holding surface via digital thermostat controller (optional)",
            "Optional white frame for aesthetic versatility",
            "Advanced control box with ON/OFF rocker switch and mounting brackets",
            "Available in black or white ceramic glass",
            "User friendly interface with digital controller",
        ],
        models: [
            {
                model: "CBS3838",
                description: "Ceramic + Hotplate",
                dimensions: { L: 380, W: 380, H: 90 },
                voltage: "230V",
                power: "450W",
                cut_out_size_AXB: "388x388",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS4040",
                description: "Ceramic + Hotplate",
                dimensions: { L: 400, W: 400, H: 90 },
                voltage: "230V",
                power: "500W",
                cut_out_size_AXB: "408x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS6040",
                description: "Ceramic + Hotplate",
                dimensions: { L: 600, W: 400, H: 90 },
                voltage: "230V",
                power: "750W",
                cut_out_size_AXB: "608x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS6050",
                description: "Ceramic + Hotplate",
                dimensions: { L: 600, W: 500, H: 90 },
                voltage: "230V",
                power: "1000W",
                cut_out_size_AXB: "608x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS8040",
                description: "Ceramic + Hotplate",
                dimensions: { L: 800, W: 400, H: 90 },
                voltage: "230V",
                power: "1050W",
                cut_out_size_AXB: "808x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS8050",
                description: "Ceramic + Hotplate",
                dimensions: { L: 800, W: 500, H: 90 },
                voltage: "230V",
                power: "1350W",
                cut_out_size_AXB: "808x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS9040",
                description: "Ceramic + Hotplate",
                dimensions: { L: 920, W: 400, H: 90 },
                voltage: "230V",
                power: "1200W",
                cut_out_size_AXB: "928x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS9050",
                description: "Ceramic + Hotplate",
                dimensions: { L: 920, W: 500, H: 90 },
                voltage: "230V",
                power: "1550W",
                cut_out_size_AXB: "928x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS12040",
                description: "Ceramic + Hotplate",
                dimensions: { L: 1200, W: 400, H: 90 },
                voltage: "230V",
                power: "1600W",
                cut_out_size_AXB: "1208x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS12050",
                description: "Ceramic + Hotplate",
                dimensions: { L: 1200, W: 500, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1208x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS15040",
                description: "Ceramic + Hotplate",
                dimensions: { L: 1500, W: 400, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1508x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS15050",
                description: "Ceramic + Hotplate",
                dimensions: { L: 1500, W: 500, H: 90 },
                voltage: "230V",
                power: "2600W",
                cut_out_size_AXB: "1508x508",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS18040",
                description: "Ceramic + Hotplate",
                dimensions: { L: 1843, W: 400, H: 90 },
                voltage: "230V",
                power: "2500W",
                cut_out_size_AXB: "1851x408",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CBS18050",
                description: "Ceramic + Hotplate",
                dimensions: { L: 1843, W: 500, H: 90 },
                voltage: "230V",
                power: "3200W",
                cut_out_size_AXB: "1851x580",
                controller_size_AXBxC: "160x90x80",
            }
        ],
    },
    {
        product_name: "Drop-in Ceramic Hot Plate",
        description:
            "Efficient ceramic hot plate for buffet counters with adjustable thermostat and easy installation.",
        features: [
            "Safe and efficient infrared heating",
            "Digital temperature control option",
            "Reduces mess by replacing open flame",
            "Durable ceramic glass surface",
            "Can be installed by drop-in method",
            "Ceramic inlay available in black or white",
            "Standard size compatible mounting brackets",
        ],
        models: [
            {
                model: "CDS6040",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 646, W: 446, H: 90 },
                voltage: "230V",
                power: "750W",
                cut_out_size_AXB: "610x410",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS6050",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 646, W: 546, H: 90 },
                voltage: "230V",
                power: "1000W",
                cut_out_size_AXB: "610x510",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS8040",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 846, W: 446, H: 90 },
                voltage: "230V",
                power: "1050W",
                cut_out_size_AXB: "810x410",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS8050",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 846, W: 546, H: 90 },
                voltage: "230V",
                power: "1350W",
                cut_out_size_AXB: "810x510",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS9040",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 966, W: 446, H: 90 },
                voltage: "230V",
                power: "1200W",
                cut_out_size_AXB: "930x410",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS9050",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 966, W: 546, H: 90 },
                voltage: "230V",
                power: "1550W",
                cut_out_size_AXB: "930x510",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS12040",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1246, W: 446, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "930x510",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS12050",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1246, W: 546, H: 90 },
                voltage: "230V",
                power: "1600W",
                cut_out_size_AXB: "1210x510",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS15050",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1500, W: 546, H: 90 },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1210x510",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS15550",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1546, W: 546, H: 90 },
                voltage: "230V",
                power: "2500W",
                cut_out_size_AXB: "1510x510",
                control_panel_size_AXBxC: "160x90x80",
            },
            {
                model: "CDS18050",
                description: "Ceramic + Hotplate (Drop-in Series)",
                dimensions: { L: 1889, W: 446, H: 90 },
                voltage: "230V",
                power: "3200W",
                cut_out_size_AXB: "1853x410",
                control_panel_size_AXBxC: "160x90x80",
            }
        ],
    },
    {
        product_name: "Ceramic Hot Plates with Thermal Bridge",
        description:
            "Ceramic hot plate with additional thermal bridge heating for enhanced holding and staged warming.",
        features: [
            "Built in high performance quartz lamps for pre-heating",
            "Ceramic glass surface for high storage and hygiene",
            "Temperature output from hot plate and bridge area",
            "Digital/manual temperature control options",
            "Optimal energy saving",
            "Mountable on adjustable stands",
        ],
        models: [
            {
                model: "CTB18050",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1889, W: 586, H: "90+45D" },
                voltage: "230V",
                power: "3200W",
                cut_out_size_AXB: "1809x566",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB18040",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1889, W: 486, H: "90+45D" },
                voltage: "230V",
                power: "2500W",
                cut_out_size_AXB: "1809x456",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB15050",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1546, W: 586, H: "90+45D" },
                voltage: "230V",
                power: "2500W",
                cut_out_size_AXB: "1509x546",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB15040",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1546, W: 486, H: "90+45D" },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1509x456",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB12050",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1289, W: 586, H: "90+45D" },
                voltage: "230V",
                power: "1600W",
                cut_out_size_AXB: "1209x546",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB12040",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1289, W: 486, H: "90+45D" },
                voltage: "230V",
                power: "2000W",
                cut_out_size_AXB: "1209x456",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB0950",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1006, W: 586, H: "90+45D" },
                voltage: "230V",
                power: "1550W",
                cut_out_size_AXB: "926x546",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB0940",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 1006, W: 486, H: "90+45D" },
                voltage: "230V",
                power: "1350W",
                cut_out_size_AXB: "926x456",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB08050",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 866, W: 586, H: "90+45D" },
                voltage: "230V",
                power: "1200W",
                cut_out_size_AXB: "806x546",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB08040",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 866, W: 486, H: "90+45D" },
                voltage: "230V",
                power: "1050W",
                cut_out_size_AXB: "806x456",
                controller_size_AXBxC: "160x90x80",
            },
            {
                model: "CTB06040",
                description: "Ceramic Hot Plate with Thermal Bridge",
                dimensions: { L: 686, W: 586, H: "90+45D" },
                voltage: "230V",
                power: "750W",
                cut_out_size_AXB: "606x546",
                controller_size_AXBxC: "160x90x80",
            },
        ],
    },
    {
        product_name: "Digital Electronic Touch Panel",
        description:
            "Advanced temperature control panel with precise digital adjustment for ceramic hot plates.",
        features: [
            "Touch-based operation",
            "User-friendly interface",
            "Allows precise temperature control",
            "Maintains efficiency during peak hours",
            "Automatic resume feature after power failure",
            "Compact ABS enclosure with IP65 protection",
            "Surface mountable",
        ],
        models: [],
    },
    {
        product_name: "Analog Infinity Controller",
        description:
            "Analog temperature controller for ceramic hot plates offering easy and preferred manual control.",
        features: [
            "Simple knob-based control",
            "Quick to operate and safe",
            "No complicated settings",
            "Perfect for ease of use",
            "Temperature output cable for hot plate",
            "ABS enclosure with IP65 rating",
            "Moisture-resistant",
        ],
        models: [],
    },
    {
        "product_name": "Heated Decorative Lamps",
        "description": "Decorative heating lamps designed to integrate lighting and warming functionalities. These lamps enhance the overall aesthetic while providing consistent heat distribution, making them ideal for food display and serving areas in professional settings.",
        "features": [
            "Integrates decoration, lighting, and warming functions for enhanced visual appeal.",
            "Allows flexible matching with different styles and colors.",
            "Available in a wide range of shades, gloss finishes, and plated options to match décor.",
            "Features heat dissipation holes to protect the main structure and extend service life.",
            "Provides even heating and effectively inhibits bacterial growth.",
            "Suitable for hotels, restaurants, institutional food courts, staff cafeterias, and similar environments.",
            "Standard height ranges from 320mm to 3245mm with customizable options.",
            "Complies with safety, health, environmental, and hygiene standards."
        ],
        models: [
            {
                model: "SKS-400-TL",
                diameter_mm: 180,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-500-TL",
                diameter_mm: 165,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-600-TL",
                diameter_mm: 175,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-700-TL",
                diameter_mm: 175,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-725-TL",
                diameter_mm: 240,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-750-TL",
                diameter_mm: 265,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-775-TL",
                diameter_mm: 265,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-800-TL",
                diameter_mm: 285,
                height_mm: "720-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-400-ML",
                diameter_mm: 180,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-500-ML",
                diameter_mm: 165,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-600-ML",
                diameter_mm: 175,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-700-ML",
                diameter_mm: 175,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-725-ML",
                diameter_mm: 240,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-750-ML",
                diameter_mm: 265,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-775-ML",
                diameter_mm: 265,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-800-ML",
                diameter_mm: 285,
                height_mm: "320-2445",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-400-ST",
                diameter_mm: 180,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-500-ST",
                diameter_mm: 165,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-600-ST",
                diameter_mm: 175,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-700-ST",
                diameter_mm: 175,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-725-ST",
                diameter_mm: 240,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-750-ST",
                diameter_mm: 265,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-775-ST",
                diameter_mm: 265,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
            {
                model: "SKS-800-ST",
                diameter_mm: 285,
                height_mm: "950-1800",
                voltage: "220V",
                power: "250W",
                colour_choices: "Multiple",
            },
        ],
    },
];
